# Generated by Django 5.0.3 on 2024-03-19 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_city_alter_trip_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.city'),
        ),
    ]
