# Generated by Django 5.0.3 on 2024-03-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_trip_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='price_efort',
            new_name='price_confort',
        ),
    ]
